### PR TITLE
Install slurm using rpm

### LINKED ISSUE #14: Switch to rpm install for slurm
@buttermutter pointed out Slurm can be installed in a way that is simpler and more in sync with how we do things in production.
Quoting from the [slurm docs](https://slurm.schedmd.com/quickstart_admin.html):

```
NOTE: Items 3 through 8 can be replaced with

    rpmbuild -ta slurm*.tar.bz2
    rpm --install <the rpm files>
```

### PR DESCRIPTION
**Pull request by djperrefort**
Replaces make commands with rpm commands for installing slurm

### CODE REVIEW

**Comment by djperrefort** [comment]
@buttermutter I've added the rpm files for slurm 20.02.5.1. I wasn't sure if the files in the `srpms` needed to be included. Can you clarify if they are necessary? Right now I'm leaving them out.

Can you please generate rpms for the other versions using the same method/environment as before?

**Comment by buttermutter** [comment]
@djperrefort it's correct to omit the srpm, only copied it over for completeness as it's a byproduct of the rpm build process.  .srpm is the most common way to distribute rpm sources, but are only used at compile not run time, the intent being if you modify anything it'll be sucked into in the new srpm for further distribution.  (but in this case we didn't modify anything.)

Yes, we'll generate the other rpms and document the build env/process used.

**Comment by buttermutter** [comment]
Rpms for 20.11.9 22.05.2 and 22.05.3 (just in case) are under /ihome/cssd/shared/slurm.

We could make a yum repo for these if desired.  Build notes to follow.

**Review by iamtroy412 — APPROVED** [review]
lgtm

**Pull request merged**
