### PR TITLE
Multi-stage docker build

### PR DESCRIPTION
**Pull request by iamtroy412**
This PR is for a multi-stage docker build of the slurm test environment. This will allow us to remove the static RPMs from git and build them as new slurm versions are added to the test list. The first stage installs the required `devel` packages for all possible plugins then builds the slurm RPMs. The second stage copies in the slurm RPMs from the first stage and installs them. 

- Removes version `20.02.5`. As slurm versions are removed from the [download archive](https://download.schedmd.com/slurm/), they should be dropped from testing
- Add version `22.05.11`, the version currently running on the cluster
- Removed rpms from git
- Build and install the `slurmrestd` package by default

Tested locally using;
`podman build -t slurm-test-env:22.05.11 -f Dockerfile --build-arg SLURM_VERSION=22.05.11`
`podman run -it --rm -v ./tests/:/tests localhost/slurm-test-env:22.05.11 bats /tests`

### CODE REVIEW

**Comment by iamtroy412** [comment]
github actions files need to be updated, but wanted to get any feedback from testing locally first.

**Review by djperrefort — COMMENTED** [review]
Changes to the docker file look good. Doesn't the entrypoint script need updating to launch the rest API daemon? I tried running the `slurmrestd` command from within the container but I get the following error:

```
slurmrestd: fatal: Unable to unshare System V namespace: Operation not permitted
```

**Comment by iamtroy412** [comment]
Yeah, the entrypoint script needs to be updated, as well as the `slurm.conf` files to enable the JWT auth to the slurmctld daemon. I'd like to address that in a different PR though, and keep this one just to the multi-stage build and building/installing the slurmrestd package. I'll reference #116 in a new PR that sets up and configures the rest daemon.

**Comment by djperrefort** [comment]
SGTM. Merge at will.

**Pull request merged**
