### PR TITLE
Update slurm conf

### LINKED ISSUE #16: Update config files to more closly reflect production server
Current config files were copied from [an online example](https://github.com/giovtorres/docker-centos6-slurm). They should be updated to more closely resemble what we actually use.

### PR DESCRIPTION
**Pull request by iamtroy412**
This will close #16.

Updated the slurm configuration files with what we currently have running on our DB host and SMP head node. I removed any references to compute nodes, controller and database hostnames/IP address, internal filesystems, and some of the old "BARRY" comments.

### CODE REVIEW

**Comment by iamtroy412** [comment]
On slurm version `22.*`, `slurmctld` fails to start because `SchedulerPort` is no longer supported as of [Slurm `21.08.0rc1`](https://github.com/SchedMD/slurm/blob/master/NEWS#L997)

```
Starting slurmctld...
slurmctld: error: _parse_next_key: Parsing error at unrecognized key: SchedulerPort
slurmctld: fatal: The AccountingStoreJobComment option has been removed, please use AccountingStoreFlags=job_comment option instead.
sacctmgr: error: _parse_next_key: Parsing error at unrecognized key: SchedulerPort
sacctmgr: fatal: The AccountingStoreJobComment option has been removed, please use AccountingStoreFlags=job_comment option instead.
Error: Process completed with exit code 1.
```

**Comment by djperrefort** [comment]
@iamtroy412 Do you want a review now or should I wait until this is no longer marked as a draft? I was assuming the latter.

**Comment by iamtroy412** [comment]
Yes, pleas wait a bit. I was hoping to merge the changes from #23 when it's ready into this branch. Using the generated RPMs should remove one of the issues with trying to use our current slurm configs.

`slurmctld: error: On FrontEnd systems TaskPlugin=task/none is required`

**Comment by djperrefort** [comment]
I'm working on #23 today. I'll let you know once it's good to go.

**Comment by iamtroy412** [comment]
Changed syntax of one of the options for the 22+ version of slurm.

`slurmctld: fatal: The AccountingStoreJobComment option has been removed, please use AccountingStoreFlags=job_comment option instead.`

**Comment by iamtroy412** [comment]
Between slurm versions 20 and 22, the `Sched` option for `TaskPluginParam` was removed.

`slurmctld: error: Bad TaskPluginParam: Sched`

I don't see any reference to this in the change logs, so not sure what it's previous purpose/functionality was, but it's not an available option in the man pages as of now.

https://slurm.schedmd.com/slurm.conf.html#OPT_TaskPluginParam

**Review by djperrefort — APPROVED** [review]

**Pull request merged**
